### PR TITLE
mintyard low health notification

### PR DESCRIPTION
**Pull request by pe-matsushita**
mintyard low health notification (in development)

### CODE REVIEW

**Review by daviddayag — COMMENTED** [review]
hi, can you set dev=true for this project so we can push it to experimental mode?
if it works as expected you can later set dev false

**Comment by daviddayag** [comment]
I see that the url is at cloudfront,
is this a wip project?

**Comment by pe-matsushita** [comment]
Thank you for your review.Our project is still a work in progress.
I've set dev flag and sent a new pull request.

**Review by daviddayag — CHANGES_REQUESTED** [review]
thank you, can you also change the logo?
it seems like binance logo now, and that might be confusing.
experimental mode (dev=true) is set to allow people try experimental notifications at their own risk, but we dont want them to be confused.

**Comment by pe-matsushita** [comment]
I apologize for the delay.
Our project name has been changed to "LootBridge".
And we made new logo.
Please review again.

**Review by daviddayag — APPROVED** [review]

**Comment by daviddayag** [comment]
Done, should be up in a few minutes

**Pull request merged**
